#!/usr/bin/env python3
"""Bake Inconsolata (OFL) into font_aa.h: 8-bit-alpha glyph cells, ASCII 32-126.

Each font is a flat array of fixed-size cells (cellW x cellH bytes, one alpha
byte per pixel), glyph = cells[ch - 32]. Monospaced, so layout is trivial on
the device. Run from tools/:  python3 gen_font.py
"""
from PIL import Image, ImageDraw, ImageFont

FONTS = [
    # (C name, ttf path, px size)
    ("kFontSmall", "/Library/Fonts/Inconsolata_Regular.ttf", 15),
    ("kFontSmallBold", "/Library/Fonts/Inconsolata_Bold.ttf", 15),
    ("kFontBig", "/Library/Fonts/Inconsolata_Bold.ttf", 22),
]
FIRST, LAST = 32, 126


def bake(cname, path, px):
    font = ImageFont.truetype(path, px)
    ascent, descent = font.getmetrics()
    cell_h = ascent + descent
    cell_w = int(round(font.getlength("M"))) + 1  # +1 for slight overhangs
    bits = bytearray()
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (cell_w, cell_h), 0)
        ImageDraw.Draw(img).text((0, 0), chr(code), font=font, fill=255)
        bits += img.tobytes()
    return cell_w, cell_h, bytes(bits)


def emit(out):
    out.write("// Generated by tools/gen_font.py -- do not edit.\n")
    out.write("// Inconsolata (SIL Open Font License), 8-bit alpha cells, ASCII 32-126.\n")
    out.write("#pragma once\n#include <cstdint>\n\n")
    out.write("namespace gfx { struct AAFontDesc; }\n\n")
    decls = []
    for cname, path, px in FONTS:
        w, h, bits = bake(cname, path, px)
        arr = f"{cname}_bits"
        out.write(f"static const uint8_t {arr}[] = {{\n")
        for i in range(0, len(bits), 24):
            out.write("  " + ",".join(str(b) for b in bits[i:i + 24]) + ",\n")
        out.write("};\n")
        decls.append((cname, arr, w, h))
        print(f"{cname}: {px}px -> cell {w}x{h}, {len(bits)} bytes")
    out.write("\n#include \"gfx.h\"\n")
    for cname, arr, w, h in decls:
        out.write(f"static const gfx::AAFontDesc {cname} = {{{arr}, {w}, {h}}};\n")


with open("../font_aa.h", "w") as f:
    emit(f)
print("wrote ../font_aa.h")
