#!/usr/bin/env python3
"""Generate audio_clips.h -- the tracker sounds, fully synthesized.

Both sounds are resynthesized versions of the Aliens motion-tracker effects:
each is a pure sine tone shaped by an amplitude envelope measured (5 ms
narrowband RMS) from a reference recording of the scene. No third-party audio
is embedded -- the tables below are just measurements.

  blip    -- 1675 Hz search ping + soft echo-pip (~330 ms), idle scanning
  contact -- 2075 Hz swell ping (~210 ms), target detected; the firmware
             resamples it 0.807x..1.036x so it sweeps 1675 -> 2150 Hz as
             the target closes, matching the reference scene.

Usage: python3 gen_audio.py   (no arguments; writes ../audio_clips.h)
"""
import math, os

OUT_RATE = 16000
PEAK = 0.92
ENV_STEP_MS = 2.5

# True envelopes from coherent I/Q demodulation (250 Hz lowpass) of the
# reference scene, 2.5 ms steps, full double-pulse window: main ping, then
# its echo pulse ~200 ms later. The slow undulation through the ping body
# is the real ~6-9 Hz warble -- measured, not synthetic; do not smooth it.
CONTACT_FREQ = 2075
CONTACT_ENV = [
            0.0, 0.056, 0.026, 0.113, 0.029, 0.069, 0.196, 0.116, 0.225, 0.206,
            0.219, 0.361, 0.247, 0.345, 0.314, 0.32, 0.419, 0.409, 0.398, 0.433,
            0.477, 0.553, 0.531, 0.523, 0.638, 0.545, 0.646, 0.634, 0.645, 0.761,
            0.715, 0.734, 0.84, 0.669, 0.809, 0.871, 0.73, 0.927, 0.873, 0.841,
            0.916, 0.814, 0.872, 0.908, 0.763, 0.917, 0.853, 0.854, 1.0, 0.906,
            0.905, 0.939, 0.778, 0.909, 0.856, 0.791, 0.987, 0.738, 0.818, 0.833,
            0.643, 0.755, 0.682, 0.648, 0.698, 0.579, 0.553, 0.592, 0.514, 0.56,
            0.592, 0.379, 0.385, 0.377, 0.28, 0.234, 0.242, 0.216, 0.104, 0.16,
            0.087, 0.083, 0.081, 0.082, 0.041, 0.019, 0.046, 0.087, 0.064, 0.019,
            0.032, 0.018, 0.09, 0.044, 0.102, 0.022, 0.048, 0.076, 0.061, 0.012,
            0.086, 0.03, 0.011, 0.141, 0.047, 0.118, 0.1, 0.092, 0.126, 0.062,
            0.085, 0.19, 0.178, 0.171, 0.317, 0.117, 0.261, 0.285, 0.209, 0.29,
            0.305, 0.297, 0.327, 0.315, 0.275, 0.338, 0.336, 0.26, 0.389, 0.315,
            0.344, 0.327, 0.275, 0.297, 0.277, 0.297, 0.301, 0.273, 0.282, 0.235,
            0.194, 0.145, 0.138, 0.146, 0.119, 0.11, 0.094, 0.058, 0.064, 0.052,
            0.1, 0.05, 0.106, 0.089, 0.049, 0.103, 0.089, 0.009, 0.028, 0.033,
            0.027, 0.042, 0.018, 0.008, 0.044, 0.066, 0.05, 0.0,
]

BLIP_FREQ = 1675
BLIP_ENV = [
            0.0, 0.232, 0.36, 0.378, 0.382, 0.38, 0.433, 0.464, 0.517, 0.528,
            0.578, 0.63, 0.696, 0.766, 0.79, 0.817, 0.778, 0.788, 0.809, 0.81,
            0.878, 0.847, 0.882, 0.856, 0.848, 0.866, 0.789, 0.783, 0.728, 0.733,
            0.736, 0.696, 0.712, 0.647, 0.658, 0.597, 0.594, 0.556, 0.529, 0.523,
            0.504, 0.516, 0.49, 0.475, 0.437, 0.403, 0.385, 0.336, 0.303, 0.258,
            0.228, 0.182, 0.136, 0.112, 0.105, 0.093, 0.071, 0.038, 0.0, 0.0,
            0.0, 0.0, 0.0, 0.0, 0.043, 0.053, 0.037, 0.0, 0.042, 0.039,
            0.082, 0.08, 0.086, 0.064, 0.052, 0.059, 0.064, 0.076, 0.103, 0.098,
            0.122, 0.12, 0.152, 0.177, 0.206, 0.191, 0.186, 0.195, 0.22, 0.24,
            0.247, 0.281, 0.284, 0.292, 0.305, 0.315, 0.323, 0.324, 0.337, 0.329,
            0.305, 0.288, 0.29, 0.298, 0.303, 0.303, 0.305, 0.294, 0.294, 0.263,
            0.246, 0.218, 0.211, 0.229, 0.224, 0.241, 0.215, 0.198, 0.159, 0.135,
            0.105, 0.082, 0.058, 0.049, 0.06, 0.051, 0.065, 0.047, 0.061, 0.046,
            0.035, 0.038, 0.043, 0.046, 0.0, 0.0,
]

def synth(freq, env):
    n = int((len(env) - 1) * ENV_STEP_MS * OUT_RATE / 1000)
    step = 1000.0 / (ENV_STEP_MS * OUT_RATE)  # env points per sample
    out = []
    for i in range(n):
        p = i * step
        j = int(p)
        fr = p - j
        e = env[j] * (1 - fr) + env[j + 1] * fr
        out.append(e * math.sin(2 * math.pi * freq * i / OUT_RATE))
    g = PEAK * 32767.0 / max(abs(x) for x in out)
    return [max(-32768, min(32767, int(round(x * g)))) for x in out]

def main():
    clips = [("kClipBlip", synth(BLIP_FREQ, BLIP_ENV)),
             ("kClipContact", synth(CONTACT_FREQ, CONTACT_ENV))]
    dst = os.path.join(os.path.dirname(__file__), "..", "audio_clips.h")
    with open(dst, "w") as f:
        f.write("#pragma once\n#include <stdint.h>\n\n")
        f.write("// Generated by tools/gen_audio.py -- do not edit.\n")
        f.write("// Synthesized motion-tracker sounds (sine + measured envelope),\n")
        f.write("// 16 kHz mono int16.\n\n")
        for name, data in clips:
            f.write(f"static const int {name}Len = {len(data)};\n")
            f.write(f"static const int16_t {name}[{len(data)}] = {{\n")
            for i in range(0, len(data), 16):
                f.write("  " + ",".join(str(v) for v in data[i:i + 16]) + ",\n")
            f.write("};\n\n")
            print(f"{name}: {len(data)} samples ({1000*len(data)//OUT_RATE} ms)")
    print(f"wrote {os.path.normpath(dst)}")

if __name__ == "__main__":
    main()
